# Generated by Django 5.0.14 on 2026-06-22 09:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credential', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='项目编码')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('version_rule', models.JSONField(default=dict, verbose_name='版本号规则')),
                ('release_rule', models.JSONField(default=dict, verbose_name='发布规则')),
                ('status', models.IntegerField(choices=[(1, '启用'), (0, '停用')], default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL, verbose_name='项目负责人')),
            ],
            options={
                'verbose_name': '项目',
                'db_table': 'sys_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration_type', models.CharField(choices=[('git_repo', 'Git仓库'), ('svn_repo', 'SVN仓库'), ('jenkins', 'Jenkins任务')], max_length=20, verbose_name='绑定类型')),
                ('vendor', models.CharField(blank=True, choices=[('gitlab', 'GitLab'), ('gitea', 'Gitea'), ('github', 'GitHub'), ('gitee', 'Gitee'), ('svn', 'SVN'), ('jenkins', 'Jenkins')], max_length=20, verbose_name='平台')),
                ('name', models.CharField(max_length=200, verbose_name='绑定名称')),
                ('external_identity', models.CharField(blank=True, max_length=500, verbose_name='外部唯一标识')),
                ('config', models.JSONField(default=dict, verbose_name='额外配置')),
                ('credential_mode', models.CharField(choices=[('current_user', '当前用户'), ('specified_user', '指定用户'), ('fixed', '项目固定凭证'), ('global', '系统全局凭证')], default='fixed', max_length=20, verbose_name='凭证使用模式')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrations', to='credential.credential', verbose_name='关联凭证')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='project.project', verbose_name='项目')),
                ('specified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specified_integrations', to=settings.AUTH_USER_MODEL, verbose_name='指定用户')),
            ],
            options={
                'verbose_name': '项目外站绑定',
                'db_table': 'sys_project_integration',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('developer', '开发人员'), ('tester', '测试人员'), ('manager', '项目管理员'), ('auditor', '审核人'), ('viewer', '只读人员')], default='developer', max_length=20, verbose_name='角色')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='project.project', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目成员',
                'db_table': 'sys_project_member',
                'unique_together': {('project', 'user')},
            },
        ),
    ]
