# Generated by Django 5.0.14 on 2026-06-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='项目编码'),
        ),
    ]
