# Generated by Django 5.0.14 on 2026-06-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins', '0002_remove_jenkinsjob_integration_jenkinsjob_repository'),
        ('project', '0002_alter_project_code'),
        ('repository', '0003_remove_repository_integration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectIntegration',
        ),
    ]
