# Generated by Django 5.0.14 on 2026-08-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_delete_projectintegration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('developer', '开发人员'), ('tester', '测试人员'), ('manager', '项目管理员'), ('auditor', '审核人'), ('viewer', '只读人员'), ('software_admin', '软件管理员')], default='developer', max_length=20, verbose_name='角色'),
        ),
    ]
