# Generated by Django 5.0.14 on 2026-09-10

import re
import uuid

import django.db.models.deletion
from django.db import migrations, models


def _as_uuid(value):
    """cursor 在 SQLite 上可能返回 str，统一成 UUID 再与 ORM 主键比对。"""
    if value is None:
        return None
    if isinstance(value, uuid.UUID):
        return value
    return uuid.UUID(str(value))


def _collect_legacy_pairs(apps, schema_editor):
    """收集应回填的产品-仓库对。

    除仓库历史 project 字段外，还读取发布单和打包配置：迁移前若已把重复
    仓库归并到主仓库，另一产品的关联只能从这些单据恢复。
    """
    Repository = apps.get_model("repository", "Repository")
    connection = schema_editor.connection
    tables = set(connection.introspection.table_names())
    repo_map = {item.id: item for item in Repository.objects.all()}
    pairs: list[tuple] = []
    seen: set[tuple] = set()

    def add_pair(project_id, repository_id):
        project_id = _as_uuid(project_id)
        repository_id = _as_uuid(repository_id)
        if not project_id or not repository_id or repository_id not in repo_map:
            return
        key = (project_id, repository_id)
        if key in seen:
            return
        seen.add(key)
        pairs.append(key)

    for repository in Repository.objects.order_by("created_at", "id"):
        # 历史迁移状态下 Repository 仍有 project 字段；getattr 兜底便于
        # 测试用当前模型直接调用本函数（Repository.project 已在后续迁移删除）。
        add_pair(getattr(repository, "project_id", None), repository.id)
    for table in ("release_record", "package_config"):
        if table not in tables:
            continue
        with connection.cursor() as cursor:
            # 当前库的 package_config 已删除旧 project/repository 冗余列（后续迁移），
            # 扫描前确认列存在；历史迁移运行时两列仍在，行为不变。
            column_names = {
                column.name
                for column in connection.introspection.get_table_description(cursor, table)
            }
            if not {"project_id", "repository_id"}.issubset(column_names):
                continue
            cursor.execute(
                f"SELECT DISTINCT project_id, repository_id FROM {table} "
                "WHERE project_id IS NOT NULL AND repository_id IS NOT NULL"
            )
            for project_id, repository_id in cursor.fetchall():
                add_pair(project_id, repository_id)
    return pairs, repo_map


def backfill_product_components(apps, schema_editor):
    """将历史“仓库直接归属项目”数据回填为产品组件关系。"""
    ProductComponent = apps.get_model("project", "ProductComponent")
    pairs, repo_map = _collect_legacy_pairs(apps, schema_editor)

    used_codes: dict[uuid.UUID, set[str]] = {}
    for project_id, repository_id in pairs:
        repository = repo_map[repository_id]
        project_codes = used_codes.setdefault(project_id, set())
        base_code = re.sub(r"[^a-z0-9._-]+", "-", (repository.name or "").lower()).strip("-._")
        base_code = (base_code or f"repo-{str(repository.id)[:8]}")[:100]
        component_code = base_code
        suffix = 2
        while component_code in project_codes:
            suffix_text = f"-{suffix}"
            component_code = f"{base_code[:100 - len(suffix_text)]}{suffix_text}"
            suffix += 1
        project_codes.add(component_code)
        ProductComponent.objects.create(
            project_id=project_id,
            repository_id=repository.id,
            component_code=component_code,
            display_name=repository.name,
            default_branch=repository.default_branch or "main",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_alter_projectmember_role"),
        ("repository", "0008_repository_version_rule"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductComponent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("component_code", models.CharField(max_length=100, verbose_name="组件编码")),
                ("display_name", models.CharField(max_length=200, verbose_name="组件名称")),
                ("default_branch", models.CharField(default="main", max_length=200, verbose_name="产品默认分支")),
                ("source_subdir", models.CharField(blank=True, default="", max_length=300, verbose_name="源码子目录")),
                ("required", models.BooleanField(default=True, verbose_name="是否必选组件")),
                ("version_scope", models.CharField(choices=[("repository", "仓库统一版本"), ("product_component", "产品组件独立版本")], default="repository", max_length=30, verbose_name="版本作用域")),
                ("tag_namespace", models.CharField(blank=True, default="", max_length=200, verbose_name="Tag 命名空间")),
                ("product_config", models.JSONField(blank=True, default=dict, verbose_name="产品内配置")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="product_components", to="project.project", verbose_name="所属产品")),
                ("repository", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="product_components", to="repository.repository", verbose_name="物理仓库")),
            ],
            options={
                "verbose_name": "产品组件",
                "verbose_name_plural": "产品组件",
                "db_table": "project_component",
                "ordering": ["sort_order", "created_at"],
                "indexes": [
                    models.Index(fields=["project", "is_active"], name="project_com_project_39a8d4_idx"),
                    models.Index(fields=["repository", "is_active"], name="project_com_reposit_d08ae5_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("project", "component_code"), name="uniq_product_component_code"),
                    models.UniqueConstraint(fields=("project", "repository"), name="uniq_product_component_repository"),
                ],
            },
        ),
        migrations.RunPython(backfill_product_components, migrations.RunPython.noop),
    ]
