# Generated by Django 5.0.14 on 2026-09-10 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_productcomponent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productcomponent',
            name='uniq_product_component_repository',
        ),
    ]
