# Generated by Django 5.0.14 on 2026-09-17 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_rename_project_component'),
        ('repository', '0013_remove_repository_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcomponent',
            options={'ordering': ['sort_order', 'created_at'], 'verbose_name': '项目组件', 'verbose_name_plural': '项目组件'},
        ),
        migrations.AlterField(
            model_name='projectcomponent',
            name='default_branch',
            field=models.CharField(default='main', max_length=200, verbose_name='项目默认分支'),
        ),
        migrations.AlterField(
            model_name='projectcomponent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_components', to='project.project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='projectcomponent',
            name='project_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='项目内配置'),
        ),
        migrations.AlterField(
            model_name='projectcomponent',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_components', to='repository.repository', verbose_name='物理仓库'),
        ),
        migrations.AlterField(
            model_name='projectcomponent',
            name='version_scope',
            field=models.CharField(choices=[('repository', '仓库统一版本'), ('product_component', '项目组件独立版本')], default='repository', max_length=30, verbose_name='版本作用域'),
        ),
    ]
