# Generated by Django 5.0.14 on 2026-08-25 00:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_operationlog_description_operationlog_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Token哈希')),
                ('token_prefix', models.CharField(editable=False, max_length=16, verbose_name='Token前缀')),
                ('scopes', models.JSONField(default=list, verbose_name='接口范围')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最近使用时间')),
                ('last_used_ip', models.CharField(blank=True, max_length=100, verbose_name='最近使用IP')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_tokens', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '访问令牌',
                'db_table': 'sys_access_token',
                'ordering': ['-created_at'],
            },
        ),
    ]
