# Generated by Django 5.0.14 on 2026-07-29 02:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('category', models.CharField(choices=[('suggestion', '功能建议'), ('bug', '问题反馈'), ('experience', '体验优化'), ('other', '其他')], default='suggestion', max_length=20, verbose_name='分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='点赞用户')),
            ],
            options={
                'verbose_name': '使用反馈',
                'verbose_name_plural': '使用反馈',
                'db_table': 'feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'created_at'], name='feedback_categor_c6d468_idx')],
            },
        ),
    ]
