# Generated by Django 5.0.14 on 2026-06-22 09:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='凭证名称')),
                ('cred_type', models.CharField(choices=[('gitlab_token', 'GitLab Token'), ('gitea_token', 'Gitea Token'), ('svn_password', 'SVN 密码'), ('jenkins_token', 'Jenkins Token'), ('ldap_password', 'LDAP 密码'), ('ai_api_key', 'AI API Key')], max_length=30, verbose_name='凭证类型')),
                ('auth_mode', models.CharField(choices=[('token', 'Token'), ('password', '用户名密码')], max_length=20, verbose_name='认证模式')),
                ('encrypted_data', models.TextField(verbose_name='加密数据')),
                ('username', models.CharField(blank=True, max_length=200, verbose_name='用户名/备注')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('scope', models.CharField(choices=[('personal', '个人'), ('project', '项目'), ('global', '全局')], default='personal', max_length=20, verbose_name='作用范围')),
                ('is_global', models.BooleanField(default=False, verbose_name='是否全局')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credentials', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL, verbose_name='归属用户')),
            ],
            options={
                'verbose_name': '凭证',
                'db_table': 'sys_credential',
                'ordering': ['-created_at'],
            },
        ),
    ]
