# Generated by Django 5.0.14 on 2026-06-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='cred_type',
            field=models.CharField(choices=[('gitlab_token', 'GitLab Token'), ('gitea_token', 'Gitea Token'), ('svn_password', 'SVN 密码'), ('jenkins_token', 'Jenkins Token'), ('ldap_password', 'LDAP 密码')], max_length=30, verbose_name='凭证类型'),
        ),
    ]
