# Generated by Codex
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credential", "0004_retire_global_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="cred_type",
            field=models.CharField(
                choices=[
                    ("gitlab_token", "GitLab Token"),
                    ("gitea_token", "Gitea Token"),
                    ("svn_password", "SVN 密码"),
                    ("ldap_password", "LDAP 密码"),
                ],
                max_length=30,
                verbose_name="凭证类型",
            ),
        ),
    ]
