# Generated by Django：凭证类型收敛，移除 Gitea Token
#
# 代码仓库平台统一为 GitLab，Gitea 不再支持，对应凭证类型一并移除。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credential", "0005_remove_jenkins_credential_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="cred_type",
            field=models.CharField(
                choices=[
                    ("gitlab_token", "GitLab Token"),
                    ("svn_password", "SVN 密码"),
                    ("ldap_password", "LDAP 密码"),
                ],
                max_length=30,
                verbose_name="凭证类型",
            ),
        ),
    ]
