# Generated by Django 5.0.14 on 2026-08-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0007_personal_only_svn_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='cred_type',
            field=models.CharField(choices=[('gitlab_token', 'GitLab Token'), ('svn_password', 'SVN 密码'), ('ldap_password', 'LDAP 密码'), ('windows_password', 'Windows 密码')], max_length=30, verbose_name='凭证类型'),
        ),
    ]
