# Generated by Django 5.0.14 on 2026-09-10 02:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0009_alter_credential_cred_type'),
        ('project', '0006_remove_productcomponent_uniq_product_component_repository'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryCredentialLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_scope', models.JSONField(default=list, help_text='可选值：read、create_tag、delete_tag', verbose_name='授权操作')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='授权过期时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '仓库凭证借用',
                'verbose_name_plural': '仓库凭证借用',
                'db_table': 'repository_credential_loan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CredentialUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=50, verbose_name='操作')),
                ('result', models.CharField(choices=[('success', '成功'), ('failure', '失败')], max_length=20, verbose_name='结果')),
                ('failure_reason', models.TextField(blank=True, verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='使用时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_logs', to='credential.credential', verbose_name='凭证')),
                ('lender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lent_credential_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='出借人')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential_usage_logs', to='project.project', verbose_name='产品')),
                ('product_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential_usage_logs', to='project.productcomponent', verbose_name='产品组件')),
            ],
            options={
                'verbose_name': '凭证使用审计',
                'verbose_name_plural': '凭证使用审计',
                'db_table': 'credential_usage_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
