# Generated by Django 5.0.14 on 2026-09-10 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0010_repositorycredentialloan_credentialusagelog'),
        ('project', '0006_remove_productcomponent_uniq_product_component_repository'),
        ('repository', '0009_repository_project_compatibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialusagelog',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential_usage_logs', to='repository.repository', verbose_name='仓库'),
        ),
        migrations.AddField(
            model_name='repositorycredentialloan',
            name='allowed_products',
            field=models.ManyToManyField(related_name='credential_loans', to='project.project', verbose_name='允许使用的产品'),
        ),
        migrations.AddField(
            model_name='repositorycredentialloan',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repository_loans', to='credential.credential', verbose_name='凭证'),
        ),
        migrations.AddField(
            model_name='repositorycredentialloan',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credential_loans', to=settings.AUTH_USER_MODEL, verbose_name='出借人'),
        ),
        migrations.AddField(
            model_name='repositorycredentialloan',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_loans', to='repository.repository', verbose_name='仓库'),
        ),
        migrations.AddField(
            model_name='credentialusagelog',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='credential.repositorycredentialloan', verbose_name='借用记录'),
        ),
        migrations.AddIndex(
            model_name='repositorycredentialloan',
            index=models.Index(fields=['repository', 'is_active'], name='repository__reposit_5a82f7_idx'),
        ),
        migrations.AddIndex(
            model_name='repositorycredentialloan',
            index=models.Index(fields=['lender', 'is_active'], name='repository__lender__b245cb_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialusagelog',
            index=models.Index(fields=['credential', 'created_at'], name='credential__credent_9043c4_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialusagelog',
            index=models.Index(fields=['product', 'created_at'], name='credential__product_0d3b77_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialusagelog',
            index=models.Index(fields=['repository', 'created_at'], name='credential__reposit_a3bf6e_idx'),
        ),
    ]
