# Generated by Django 5.0.14 on 2026-09-17 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0013_rename_project_fields'),
        ('project', '0009_alter_projectcomponent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialusagelog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential_usage_logs', to='project.project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='credentialusagelog',
            name='project_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential_usage_logs', to='project.projectcomponent', verbose_name='项目组件'),
        ),
        migrations.AlterField(
            model_name='repositorycredentialloan',
            name='allowed_projects',
            field=models.ManyToManyField(related_name='credential_loans', to='project.project', verbose_name='允许使用的项目'),
        ),
    ]
