# Generated by Django 5.0.14 on 2026-06-23 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credential', '0002_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repo_type', models.CharField(choices=[('git', 'Git'), ('svn', 'SVN')], max_length=10, verbose_name='仓库类型')),
                ('vendor', models.CharField(choices=[('gitlab', 'GitLab'), ('gitea', 'Gitea'), ('github', 'GitHub'), ('gitee', 'Gitee'), ('svn', 'SVN')], max_length=20, verbose_name='平台')),
                ('name', models.CharField(max_length=200, verbose_name='仓库名称')),
                ('url', models.CharField(max_length=500, verbose_name='仓库地址')),
                ('external_identity', models.CharField(blank=True, max_length=500, verbose_name='外部唯一标识')),
                ('default_branch', models.CharField(default='main', max_length=200, verbose_name='默认分支')),
                ('credential_mode', models.CharField(choices=[('current_user', '当前用户'), ('specified_user', '指定用户'), ('fixed', '项目固定凭证'), ('global', '系统全局凭证')], default='fixed', max_length=20, verbose_name='凭证使用模式')),
                ('health_status', models.CharField(choices=[('healthy', '健康'), ('unhealthy', '异常'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='健康状态')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='credential.credential', verbose_name='关联凭证')),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='project.projectintegration', verbose_name='外站绑定')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='project.project', verbose_name='项目')),
                ('specified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specified_repositories', to=settings.AUTH_USER_MODEL, verbose_name='指定用户')),
            ],
            options={
                'verbose_name': '代码仓库',
                'verbose_name_plural': '代码仓库',
                'db_table': 'sys_repo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommitRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commit_hash', models.CharField(max_length=100, verbose_name='提交哈希')),
                ('author', models.CharField(max_length=200, verbose_name='提交人')),
                ('author_email', models.CharField(blank=True, max_length=200, verbose_name='提交人邮箱')),
                ('message', models.TextField(verbose_name='原始提交信息')),
                ('committed_at', models.DateTimeField(verbose_name='提交时间')),
                ('branch', models.CharField(blank=True, max_length=200, verbose_name='所属分支')),
                ('parsed_message', models.JSONField(default=dict, verbose_name='解析结果')),
                ('review_status', models.CharField(choices=[('unreviewed', '未审查'), ('pass', '通过'), ('warning', '警告'), ('illegal', '非法')], default='unreviewed', max_length=20, verbose_name='审查状态')),
                ('review_reason', models.TextField(blank=True, verbose_name='审查说明')),
                ('ai_suggestion', models.TextField(blank=True, verbose_name='AI 建议')),
                ('ai_review_at', models.DateTimeField(blank=True, null=True, verbose_name='AI 审查时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='project.project', verbose_name='项目')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='repository.repository', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '提交记录',
                'verbose_name_plural': '提交记录',
                'db_table': 'repo_commit',
                'ordering': ['-committed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['project', 'repo_type'], name='sys_repo_project_37f35e_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['project', 'vendor'], name='sys_repo_project_923219_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['health_status'], name='sys_repo_health__b84584_idx'),
        ),
        migrations.AddIndex(
            model_name='commitrecord',
            index=models.Index(fields=['project', 'review_status'], name='repo_commit_project_b78093_idx'),
        ),
        migrations.AddIndex(
            model_name='commitrecord',
            index=models.Index(fields=['project', 'branch'], name='repo_commit_project_cacde3_idx'),
        ),
        migrations.AddIndex(
            model_name='commitrecord',
            index=models.Index(fields=['project', 'author'], name='repo_commit_project_4350a6_idx'),
        ),
        migrations.AddIndex(
            model_name='commitrecord',
            index=models.Index(fields=['project', 'committed_at'], name='repo_commit_project_8f48e6_idx'),
        ),
        migrations.AddIndex(
            model_name='commitrecord',
            index=models.Index(fields=['repository', 'committed_at'], name='repo_commit_reposit_c25b49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commitrecord',
            unique_together={('repository', 'commit_hash')},
        ),
    ]
