# Generated by Django 5.0.14 on 2026-06-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitrecord',
            name='ai_review_at',
        ),
        migrations.RemoveField(
            model_name='commitrecord',
            name='ai_suggestion',
        ),
    ]
