# Generated by Django 5.0.14 on 2026-06-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_remove_commitrecord_ai_review_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='integration',
        ),
    ]
