# Generated by Django 5.0.14 on 2026-07-16 01:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_repository_credential_mode_simplify'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='分支名称')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认分支')),
                ('last_commit_hash', models.CharField(blank=True, max_length=100, verbose_name='最新提交哈希')),
                ('last_commit_author', models.CharField(blank=True, max_length=200, verbose_name='最新提交人')),
                ('last_commit_message', models.TextField(blank=True, verbose_name='最新提交信息')),
                ('last_commit_at', models.DateTimeField(blank=True, null=True, verbose_name='最新提交时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='repository.repository', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '仓库分支',
                'verbose_name_plural': '仓库分支',
                'db_table': 'repo_branch',
                'ordering': ['-is_default', '-last_commit_at'],
                'indexes': [models.Index(fields=['repository', 'name'], name='repo_branch_reposit_71bff1_idx'), models.Index(fields=['repository', 'last_commit_at'], name='repo_branch_reposit_d233f9_idx')],
                'unique_together': {('repository', 'name')},
            },
        ),
    ]
