# Generated by Django：仓库平台收敛为 GitLab only
#
# 代码仓库仅支持 GitLab；SVN 仅作为打包产物推送目标（见 apps.package），
# 不再作为代码仓库接入类型。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0005_repositorybranch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="repo_type",
            field=models.CharField(
                choices=[("git", "Git")],
                max_length=10,
                verbose_name="仓库类型",
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="vendor",
            field=models.CharField(
                choices=[("gitlab", "GitLab")],
                max_length=20,
                verbose_name="平台",
            ),
        ),
    ]
