# Generated by Django 5.0.14 on 2026-07-30 08:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_gitlab_only_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Tag 名称')),
                ('commit_hash', models.CharField(blank=True, max_length=100, verbose_name='提交哈希')),
                ('major', models.IntegerField(blank=True, null=True, verbose_name='主版本号')),
                ('minor', models.IntegerField(blank=True, null=True, verbose_name='次版本号')),
                ('patch', models.IntegerField(blank=True, null=True, verbose_name='修订版本号')),
                ('suffix', models.CharField(blank=True, max_length=50, verbose_name='类型后缀')),
                ('tag_date', models.DateField(blank=True, null=True, verbose_name='Tag 日期')),
                ('remote_created_at', models.DateTimeField(blank=True, null=True, verbose_name='远端创建时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='repository.repository', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '仓库 Tag',
                'verbose_name_plural': '仓库 Tag',
                'db_table': 'repo_tag',
                'ordering': ['-major', '-minor', '-patch', '-tag_date'],
                'indexes': [models.Index(fields=['repository', 'name'], name='repo_tag_reposit_318bd7_idx'), models.Index(fields=['repository', 'tag_date'], name='repo_tag_reposit_67a9ad_idx')],
                'unique_together': {('repository', 'name')},
            },
        ),
    ]
