# Generated by Django 5.0.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_repositorytag'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='version_rule',
            field=models.JSONField(default=dict, verbose_name='版本号规则'),
        ),
    ]
