# Generated by Django 5.0.14 on 2026-09-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_productcomponent"),
        ("repository", "0008_repository_version_rule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="repositories",
                to="project.project",
                verbose_name="历史登记项目",
            ),
        ),
    ]
