# Generated by Django 5.0.14 on 2026-09-10 02:11

from urllib.parse import urlparse

from django.db import migrations, models


def prepare_repository_identity(apps, schema_editor):
    """复制版本规则并规范仓库标识；发现重复时中止，禁止静默归并。"""
    Repository = apps.get_model("repository", "Repository")
    from django.db.models import Count

    for repository in Repository.objects.select_related("project").all().iterator():
        if not repository.version_rule and repository.project_id:
            repository.version_rule = repository.project.version_rule or {}
        url = (repository.url or "").rstrip("/")
        if repository.vendor == "gitlab" and url:
            if url.startswith("git@") and ":" in url:
                host, path = url.split("@", 1)[1].split(":", 1)
                repository.url = f"https://{host}"
                repository.external_identity = repository.external_identity or path.removesuffix(".git")
            else:
                parsed = urlparse(url)
                path = parsed.path.strip("/").removesuffix(".git")
                if parsed.scheme and parsed.netloc and path:
                    repository.url = f"{parsed.scheme}://{parsed.netloc}"
                    repository.external_identity = repository.external_identity or path
        repository.save(update_fields=["version_rule", "url", "external_identity"])

    duplicate_groups = list(
        Repository.objects.exclude(external_identity="")
        .values("vendor", "url", "external_identity")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
        .order_by("vendor", "url", "external_identity")
    )
    if duplicate_groups:
        sample = "; ".join(
            f'{item["vendor"]}:{item["url"]}/{item["external_identity"]}({item["total"]})'
            for item in duplicate_groups[:10]
        )
        raise RuntimeError(
            "检测到重复物理仓库，已中止迁移且不会修改任何数据。"
            "请先人工确认主仓库并处理冲突后重试。重复项：" + sample
        )


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0011_credentialusagelog_product_release_and_more'),
        ('package', '0028_require_package_component'),
        ('project', '0006_remove_productcomponent_uniq_product_component_repository'),
        ('repository', '0009_repository_project_compatibility'),
    ]

    operations = [
        migrations.RunPython(prepare_repository_identity, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.UniqueConstraint(
                condition=~models.Q(external_identity=""),
                fields=("vendor", "url", "external_identity"),
                name="uniq_physical_repository_identity",
            ),
        ),
    ]
