# Generated by Django 5.0.14 on 2026-09-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_repository_created_by(apps, schema_editor):
    """存量仓库回填创建者：优先凭证所有人，其次历史登记产品负责人。"""
    Repository = apps.get_model("repository", "Repository")
    for repository in Repository.objects.select_related("credential", "project").iterator():
        owner_id = None
        if repository.credential_id:
            owner_id = repository.credential.owner_id
        elif repository.project_id:
            owner_id = repository.project.leader_id
        if owner_id and not repository.created_by_id:
            repository.created_by_id = owner_id
            repository.save(update_fields=["created_by"])


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0010_repository_uniq_physical_repository_identity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_repositories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="仓库创建者",
            ),
        ),
        migrations.RunPython(backfill_repository_created_by, migrations.RunPython.noop),
    ]
