# Generated by Django 5.0.14 on 2026-06-24 09:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jenkins', '0001_initial'),
        ('project', '0001_initial'),
        ('repository', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=100, verbose_name='版本号')),
                ('tag_name', models.CharField(max_length=100, verbose_name='Tag 名称')),
                ('source_branch', models.CharField(max_length=200, verbose_name='来源分支')),
                ('target_branch', models.CharField(max_length=200, verbose_name='目标分支')),
                ('git_hash', models.CharField(blank=True, max_length=100, verbose_name='Git 哈希')),
                ('release_type', models.CharField(choices=[('formal', '正式'), ('test', '测试')], max_length=20, verbose_name='发布类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('building', '构建中'), ('auditing', '待发布'), ('released', '已发布'), ('rejected', '已驳回')], default='draft', max_length=20, verbose_name='状态')),
                ('release_doc', models.JSONField(blank=True, default=dict, verbose_name='发布说明文档')),
                ('rejected_reason', models.TextField(blank=True, verbose_name='驳回原因')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('jenkins_build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='jenkins.jenkinsbuild', verbose_name='Jenkins 构建记录')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='project.project', verbose_name='项目')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='repository.repository', verbose_name='目标仓库')),
            ],
            options={
                'verbose_name': '发布记录',
                'verbose_name_plural': '发布记录',
                'db_table': 'release_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseCommit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_included', models.BooleanField(default=True, verbose_name='是否纳入发布说明')),
                ('edited_content', models.JSONField(blank=True, default=dict, verbose_name='编辑后内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_commits', to='repository.commitrecord', verbose_name='提交记录')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_commits', to='release.releaserecord', verbose_name='发布记录')),
            ],
            options={
                'verbose_name': '发布关联提交',
                'verbose_name_plural': '发布关联提交',
                'db_table': 'release_commit',
            },
        ),
        migrations.AddIndex(
            model_name='releaserecord',
            index=models.Index(fields=['project', 'status'], name='release_rec_project_a92be6_idx'),
        ),
        migrations.AddIndex(
            model_name='releaserecord',
            index=models.Index(fields=['project', 'release_type'], name='release_rec_project_978642_idx'),
        ),
        migrations.AddIndex(
            model_name='releaserecord',
            index=models.Index(fields=['repository', 'status'], name='release_rec_reposit_2ffcb4_idx'),
        ),
        migrations.AddIndex(
            model_name='releaserecord',
            index=models.Index(fields=['version'], name='release_rec_version_392ec6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='releasecommit',
            unique_together={('release', 'commit')},
        ),
    ]
