# Generated by Django 5.0.14 on 2026-06-26 02:48

from django.db import migrations, models


def migrate_old_release_data(apps, schema_editor):
    """将旧发布流程数据迁移到新 Tag 流程枚举。"""
    ReleaseRecord = apps.get_model("release", "ReleaseRecord")
    # 旧状态 building/auditing 统一转换为 pending
    ReleaseRecord.objects.filter(status__in=["building", "auditing"]).update(status="pending")
    # 旧发布类型 test 统一转换为 beta
    ReleaseRecord.objects.filter(release_type="test").update(release_type="beta")


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0002_releaserecord_workflow_instance'),
    ]

    operations = [
        migrations.RunPython(migrate_old_release_data),
        migrations.AlterField(
            model_name='releaserecord',
            name='release_type',
            field=models.CharField(choices=[('formal', '正式'), ('rc', 'RC'), ('beta', 'Beta')], max_length=20, verbose_name='发布类型'),
        ),
        migrations.AlterField(
            model_name='releaserecord',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('released', '已发布'), ('rejected', '已驳回')], default='draft', max_length=20, verbose_name='状态'),
        ),
    ]
