# Generated by Django 5.0.14 on 2026-06-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0003_alter_releaserecord_release_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaserecord',
            name='related_changes',
            field=models.JSONField(blank=True, default=list, verbose_name='关联变更清单'),
        ),
        migrations.AddField(
            model_name='releaserecord',
            name='updates',
            field=models.JSONField(blank=True, default=list, verbose_name='变更条目'),
        ),
    ]
