# Generated by Django 5.0.14 on 2026-07-01 08:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0006_migrate_version_rule_to_structured'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaserecord',
            name='config_change_doc',
            field=models.TextField(blank=True, verbose_name='配置项变更文档'),
        ),
        migrations.AddField(
            model_name='releaserecord',
            name='has_config_changes',
            field=models.BooleanField(default=False, verbose_name='是否有配置项改动'),
        ),
        migrations.AddField(
            model_name='releaserecord',
            name='impact_desc',
            field=models.TextField(blank=True, verbose_name='影响范围说明'),
        ),
        migrations.AddField(
            model_name='releaserecord',
            name='impact_other',
            field=models.BooleanField(default=False, verbose_name='是否影响其他功能'),
        ),
        migrations.AddField(
            model_name='releaserecord',
            name='retest_passed',
            field=models.BooleanField(default=False, verbose_name='研发测试复验通过'),
        ),
        migrations.AddField(
            model_name='releaserecord',
            name='self_test_passed',
            field=models.BooleanField(default=False, verbose_name='自测试通过'),
        ),
        migrations.AlterField(
            model_name='releaserecord',
            name='release_doc',
            field=models.TextField(blank=True, verbose_name='发布说明文档'),
        ),
        migrations.CreateModel(
            name='ReleaseMergeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mr_number', models.CharField(max_length=50, verbose_name='MR 编号')),
                ('title', models.CharField(max_length=500, verbose_name='MR 标题')),
                ('description', models.TextField(blank=True, verbose_name='MR 描述')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='MR 作者')),
                ('source_branch', models.CharField(blank=True, max_length=200, verbose_name='源分支')),
                ('target_branch', models.CharField(blank=True, max_length=200, verbose_name='目标分支')),
                ('web_url', models.URLField(blank=True, verbose_name='MR 链接')),
                ('merged_at', models.DateTimeField(blank=True, null=True, verbose_name='合并时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_mrs', to='release.releaserecord', verbose_name='发布记录')),
            ],
            options={
                'verbose_name': '发布关联 MR',
                'verbose_name_plural': '发布关联 MR',
                'db_table': 'release_mr',
                'ordering': ['-merged_at', '-created_at'],
                'unique_together': {('release', 'mr_number')},
            },
        ),
    ]
