# Generated by Django：移除 ReleaseRecord 上的 Jenkins 构建外键
#
# Jenkins 模块整体下线，发布流程不再关联 Jenkins 构建记录。

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0007_releaserecord_config_change_doc_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="releaserecord",
            name="jenkins_build",
        ),
    ]
