# Generated by Django 5.0.14 on 2026-08-18 09:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0009_releaserecord_package_config_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='releaserecord',
            name='base_tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='基线 Tag'),
        ),
        migrations.CreateModel(
            name='ReleaseReviewIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='意见正文')),
                ('status', models.CharField(choices=[('open', '待整改'), ('replied', '待复核'), ('resolved', '已通过')], default='open', max_length=20, verbose_name='状态')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='通过时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_issues', to=settings.AUTH_USER_MODEL, verbose_name='意见发起人')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_issues', to='release.releaserecord', verbose_name='发布记录')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_review_issues', to=settings.AUTH_USER_MODEL, verbose_name='判定人')),
            ],
            options={
                'verbose_name': '发布文档整改意见',
                'verbose_name_plural': '发布文档整改意见',
                'db_table': 'release_review_issue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseReviewReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='回复内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_review_replies', to=settings.AUTH_USER_MODEL, verbose_name='回复人')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='release.releasereviewissue', verbose_name='整改意见')),
            ],
            options={
                'verbose_name': '整改意见回复',
                'verbose_name_plural': '整改意见回复',
                'db_table': 'release_review_reply',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='releasereviewissue',
            index=models.Index(fields=['release', 'status'], name='release_rev_release_f076cc_idx'),
        ),
    ]
