# Generated by Django 5.0.14 on 2026-10-09 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0011_releaserecord_redmine_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaserecord',
            name='source_rc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formal_promotions', to='release.releaserecord', verbose_name='来源 RC'),
        ),
        migrations.AddField(
            model_name='releaserecord',
            name='source_rc_git_hash',
            field=models.CharField(blank=True, max_length=100, verbose_name='来源 RC 提交快照'),
        ),
        migrations.AddField(
            model_name='releaserecord',
            name='source_rc_tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='来源 RC Tag 快照'),
        ),
        migrations.AddField(
            model_name='releaserecord',
            name='source_rc_version',
            field=models.CharField(blank=True, max_length=100, verbose_name='来源 RC 版本快照'),
        ),
    ]
