# Generated by Django 5.0.14 on 2026-10-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("release", "0012_releaserecord_source_rc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="releaserecord",
            name="base_git_hash",
            field=models.CharField(blank=True, max_length=100, verbose_name="正式基线提交快照"),
        ),
        migrations.AddField(
            model_name="releaserecord",
            name="changes_initialized",
            field=models.BooleanField(default=False, verbose_name="正式变更基线已固定"),
        ),
        migrations.AddField(
            model_name="releaserecord",
            name="changes_warnings",
            field=models.JSONField(blank=True, default=list, verbose_name="正式变更核验提示"),
        ),
    ]
