# Generated by Django 5.0.14 on 2026-10-10 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("release", "0013_releaserecord_base_git_hash_and_more"),
        ("repository", "0013_remove_repository_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseVersionClaim",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("release_type", models.CharField(max_length=20, verbose_name="发布类型")),
                ("base_version", models.CharField(max_length=100, verbose_name="规范化基础版本")),
                ("tag_name", models.CharField(max_length=100, verbose_name="发布 Tag")),
                ("consumed", models.BooleanField(default=False, verbose_name="已成功发布")),
                (
                    "release",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="version_claims",
                        to="release.releaserecord",
                        verbose_name="发布申请",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="repository.repository", verbose_name="仓库"
                    ),
                ),
            ],
            options={
                "db_table": "release_version_claim",
            },
        ),
        migrations.AddConstraint(
            model_name="releaseversionclaim",
            constraint=models.UniqueConstraint(
                fields=("repository", "release_type", "base_version"), name="unique_repository_release_version"
            ),
        ),
    ]
