# Generated by Django 5.0.14 on 2026-10-10 00:52

from django.db import migrations, models


def mark_existing_approvals(apps, schema_editor):
    Release = apps.get_model("release", "ReleaseRecord")
    Release.objects.filter(
        release_type="formal",
        status="pending",
        source_rc__isnull=True,
        workflow_instance__status__in=["running", "completed"],
    ).update(legacy_approval_allowed=True)


class Migration(migrations.Migration):
    dependencies = [
        ("release", "0014_releaseversionclaim_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="releaserecord",
            name="legacy_approval_allowed",
            field=models.BooleanField(default=False, editable=False, verbose_name="升级前正式审批兼容"),
        ),
        migrations.RunPython(mark_existing_approvals, migrations.RunPython.noop),
    ]
