# Generated by Django 5.0.14 on 2026-10-10 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("release", "0015_releaserecord_legacy_approval_allowed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="releaserecord",
            name="tag_cleaned_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Tag 清理时间"),
        ),
        migrations.AddField(
            model_name="releaserecord",
            name="tag_cleaned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cleaned_rc_tags",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Tag 清理人",
            ),
        ),
        migrations.AddField(
            model_name="releaserecord",
            name="tag_cleanup_reference",
            field=models.CharField(blank=True, max_length=100, verbose_name="保护正式 Tag 快照"),
        ),
        migrations.AddField(
            model_name="releaserecord",
            name="tag_cleanup_status",
            field=models.CharField(blank=True, max_length=20, verbose_name="Tag 清理状态"),
        ),
        migrations.CreateModel(
            name="ReleaseTagCleanupAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(default="attempting", max_length=30, verbose_name="结果")),
                ("message", models.TextField(blank=True, verbose_name="说明")),
                ("protected_by", models.CharField(blank=True, max_length=100, verbose_name="保护正式 Tag")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="操作时间")),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cleanup_attempts",
                        to="release.releaserecord",
                        verbose_name="RC 发布",
                    ),
                ),
            ],
            options={
                "db_table": "release_tag_cleanup_attempt",
            },
        ),
    ]
