# Generated by Django 5.0.14 on 2026-06-24 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='流程名称')),
                ('biz_type', models.CharField(choices=[('release', '发布审批')], default='release', max_length=50, verbose_name='业务类型')),
                ('graph_data', models.JSONField(default=dict, verbose_name='流程图数据')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_definitions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_definitions', to='project.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '工作流定义',
                'verbose_name_plural': '工作流定义',
                'db_table': 'workflow_definition',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('biz_type', models.CharField(max_length=50, verbose_name='业务类型')),
                ('biz_id', models.CharField(max_length=200, verbose_name='业务单据ID')),
                ('status', models.CharField(choices=[('running', '运行中'), ('completed', '已完成'), ('rejected', '已驳回'), ('revoked', '已撤销')], default='running', max_length=20, verbose_name='状态')),
                ('current_node_id', models.CharField(blank=True, default='', max_length=100, verbose_name='当前节点ID')),
                ('node_status', models.JSONField(default=dict, verbose_name='节点状态快照')),
                ('graph_data', models.JSONField(default=dict, verbose_name='实例图快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_instances', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workflow.workflowdefinition', verbose_name='关联定义')),
            ],
            options={
                'verbose_name': '工作流实例',
                'verbose_name_plural': '工作流实例',
                'db_table': 'workflow_instance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=100, verbose_name='节点ID')),
                ('node_name', models.CharField(max_length=200, verbose_name='节点名称')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已通过'), ('rejected', '已驳回'), ('transferred', '已转交')], default='pending', max_length=20, verbose_name='状态')),
                ('comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('action_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_tasks', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflow.workflowinstance', verbose_name='关联实例')),
                ('transferred_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_workflow_tasks', to=settings.AUTH_USER_MODEL, verbose_name='转交来源')),
            ],
            options={
                'verbose_name': '审批任务',
                'verbose_name_plural': '审批任务',
                'db_table': 'workflow_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['project', 'biz_type', 'is_active'], name='workflow_de_project_424371_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['biz_type', 'biz_id'], name='workflow_in_biz_typ_8c8ccf_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['status', 'created_by'], name='workflow_in_status_074797_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtask',
            index=models.Index(fields=['instance', 'node_id'], name='workflow_ta_instanc_1bbf2d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtask',
            index=models.Index(fields=['approver', 'status'], name='workflow_ta_approve_50bd5e_idx'),
        ),
    ]
