# Generated by Django 5.0.14 on 2026-06-26 06:48

from django.db import migrations, models


def migrate_graph_data_to_node_config(apps, schema_editor):
    """
    将现有 graph_data 中的 approval-node 按边顺序转换为 node_config。

    旧数据默认审批模式为或签（any）。
    """
    WorkflowDefinition = apps.get_model("workflow", "WorkflowDefinition")

    for definition in WorkflowDefinition.objects.all():
        graph_data = definition.graph_data or {}
        nodes = graph_data.get("nodes", [])
        edges = graph_data.get("edges", [])
        node_map = {n["id"]: n for n in nodes}

        # 找到开始节点
        start_node_id = None
        for node in nodes:
            if node.get("type") == "start-node":
                start_node_id = node["id"]
                break

        current_id = start_node_id
        visited = set()
        node_config = []

        while current_id and current_id not in visited:
            visited.add(current_id)
            next_id = None
            for edge in edges:
                source = edge.get("sourceNodeId") or edge.get("source")
                target = edge.get("targetNodeId") or edge.get("target")
                if source == current_id:
                    next_id = target
                    break

            if not next_id:
                break

            node = node_map.get(next_id)
            if not node:
                break

            if node.get("type") == "approval-node":
                props = node.get("properties", {})
                approver_type = props.get("approver_type", "leader")
                approvers = [{
                    "type": approver_type,
                    "user_id": props.get("user_id") or None,
                    "role": props.get("role") or None,
                }]
                text = node.get("text", "")
                if isinstance(text, dict):
                    text = text.get("value", "")

                node_config.append({
                    "node_id": node["id"],
                    "node_name": text or node["id"],
                    "approvers": approvers,
                    "mode": "any",
                })

            if node.get("type") == "end-node":
                break

            current_id = next_id

        definition.node_config = node_config
        definition.save(update_fields=["node_config"])


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdefinition',
            name='node_config',
            field=models.JSONField(default=list, verbose_name='审批链配置'),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='is_rollback',
            field=models.BooleanField(default=False, verbose_name='回退重建'),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='mode',
            field=models.CharField(choices=[('any', '或签'), ('all', '会签')], default='any', max_length=10, verbose_name='审批模式'),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='rollback_target_node_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='回退目标节点'),
        ),
        migrations.AlterField(
            model_name='workflowtask',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('approved', '已通过'), ('rejected', '已驳回'), ('transferred', '已转交'), ('rollbacked', '已回退')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.RunPython(migrate_graph_data_to_node_config, migrations.RunPython.noop),
    ]
