# Generated by Django 5.0.14 on 2026-07-01 02:42

from django.conf import settings
from django.db import migrations, models


BUILTIN_NAMES = {
    "formal": "正式发布审批",
    "rc": "RC 发布审批",
    "beta": "Beta 发布审批",
}

DEFAULT_NODE_CONFIG = [
    {
        "node_id": "approval_1",
        "node_name": "项目负责人审批",
        "approvers": [{"type": "leader"}],
        "mode": "any",
    }
]


def _build_graph_data(node_config):
    """根据审批链生成最小 LogicFlow 图数据（与引擎实现保持一致）。"""
    nodes = [
        {"id": "start", "type": "start-node", "x": 100, "y": 200, "text": "开始"},
        {"id": "end", "type": "end-node", "x": 500, "y": 200, "text": "结束"},
    ]
    edges = []
    prev = "start"
    for idx, node in enumerate(node_config):
        node_id = node.get("node_id", f"approval_{idx + 1}")
        nodes.append(
            {
                "id": node_id,
                "type": "approval-node",
                "x": 300,
                "y": 200,
                "text": node.get("node_name", f"审批节点 {idx + 1}"),
                "properties": {"approver_type": node.get("approvers", [{}])[0].get("type", "leader")},
            }
        )
        edges.append({"id": f"e_{prev}_{node_id}", "sourceNodeId": prev, "targetNodeId": node_id})
        prev = node_id
    edges.append({"id": f"e_{prev}_end", "sourceNodeId": prev, "targetNodeId": "end"})
    return {"nodes": nodes, "edges": edges}


def forward(apps, schema_editor):
    """为存量项目补齐三种发布类型内置审批流程定义。"""
    WorkflowDefinition = apps.get_model("workflow", "WorkflowDefinition")
    Project = apps.get_model("project", "Project")

    graph_data = _build_graph_data(DEFAULT_NODE_CONFIG)
    for project in Project.objects.all():
        defs = list(
            WorkflowDefinition.objects.filter(project=project, biz_type="release").order_by("created_at")
        )
        # 按顺序分配 formal/rc/beta，多余的删除
        type_order = ["formal", "rc", "beta"]
        assigned = {}
        to_delete = []
        for idx, definition in enumerate(defs):
            if idx < len(type_order):
                rt = type_order[idx]
                definition.release_type = rt
                definition.name = BUILTIN_NAMES[rt]
                definition.save(update_fields=["release_type", "name", "updated_at"])
                assigned[rt] = definition
            else:
                to_delete.append(definition.id)
        if to_delete:
            WorkflowDefinition.objects.filter(id__in=to_delete).delete()
        # 补齐缺失类型
        for rt in type_order:
            if rt in assigned:
                continue
            WorkflowDefinition.objects.create(
                project=project,
                name=BUILTIN_NAMES[rt],
                biz_type="release",
                release_type=rt,
                node_config=DEFAULT_NODE_CONFIG,
                graph_data=graph_data,
                is_active=True,
            )


def reverse(apps, schema_editor):
    """回滚时不做数据还原（仅字段还原由 Django 自动处理）。"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_delete_projectintegration"),
        ("workflow", "0002_workflowdefinition_node_config_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workflowdefinition",
            options={
                "ordering": ["release_type", "-created_at"],
                "verbose_name": "工作流定义",
                "verbose_name_plural": "工作流定义",
            },
        ),
        migrations.AddField(
            model_name="workflowdefinition",
            name="release_type",
            field=models.CharField(
                choices=[("formal", "正式"), ("rc", "RC"), ("beta", "Beta")],
                default="formal",
                max_length=20,
                verbose_name="发布类型",
            ),
        ),
        migrations.RunPython(forward, reverse),
    ]
