# Generated by Django 5.0.14 on 2026-09-17 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_projectcomponent_options_and_more'),
        ('workflow', '0008_rc_beta_skip_approval_by_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowdefinition',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_definitions', to='project.project', verbose_name='历史所属项目'),
        ),
    ]
