# Generated by Django 5.0.14 on 2026-08-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('audit', '审批通知'), ('build', '构建结果'), ('release', '发布结果'), ('review', '审查整改'), ('system', '系统通知')], max_length=20, verbose_name='通知类型'),
        ),
    ]
