# Generated by Django 5.0.14 on 2026-09-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_strong",
            field=models.BooleanField(default=False, verbose_name="强提醒"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user", "is_strong", "is_read"], name="notificatio_user_id_strong_idx"),
        ),
    ]
