# Generated by Codex
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0003_delete_projectintegration"),
        ("repository", "0004_repository_credential_mode_simplify"),
        ("release", "0007_releaserecord_config_change_doc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageImage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, verbose_name="镜像名称")),
                ("build_type", models.CharField(choices=[("web", "Web"), ("qt", "Qt")], max_length=20, verbose_name="打包类型")),
                ("image", models.CharField(max_length=500, verbose_name="Docker 镜像")),
                ("script_entry", models.CharField(default="/usr/local/bin/trace-ship-build", max_length=500, verbose_name="镜像脚本入口")),
                ("default_build_path", models.CharField(default=".", max_length=300, verbose_name="默认构建目录")),
                ("default_output_path", models.CharField(default="artifacts", max_length=300, verbose_name="默认产物目录")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "打包镜像",
                "verbose_name_plural": "打包镜像",
                "db_table": "package_image",
                "ordering": ["build_type", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PackageConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, verbose_name="配置名称")),
                ("mode", models.CharField(choices=[("simple", "简易打包"), ("local", "本地脚本")], default="simple", max_length=20, verbose_name="打包模式")),
                ("build_type", models.CharField(choices=[("web", "Web"), ("qt", "Qt")], default="web", max_length=20, verbose_name="打包类型")),
                ("local_script", models.TextField(blank=True, verbose_name="本地打包脚本")),
                ("build_path", models.CharField(blank=True, default=".", max_length=300, verbose_name="构建目录")),
                ("output_path", models.CharField(blank=True, default="artifacts", max_length=300, verbose_name="产物目录")),
                ("env_vars", models.JSONField(blank=True, default=dict, verbose_name="环境变量")),
                ("auto_package_on_release", models.BooleanField(default=False, verbose_name="发布后自动打包")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("image", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="package_configs", to="package.packageimage", verbose_name="打包镜像")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="package_configs", to="project.project", verbose_name="项目")),
                ("repository", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="package_configs", to="repository.repository", verbose_name="关联仓库")),
            ],
            options={
                "verbose_name": "打包配置",
                "verbose_name_plural": "打包配置",
                "db_table": "package_config",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PackageTask",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, verbose_name="任务名称")),
                ("mode", models.CharField(choices=[("simple", "简易打包"), ("local", "本地脚本")], max_length=20, verbose_name="打包模式")),
                ("build_type", models.CharField(choices=[("web", "Web"), ("qt", "Qt")], max_length=20, verbose_name="打包类型")),
                ("tag_name", models.CharField(max_length=100, verbose_name="Tag 名称")),
                ("version", models.CharField(max_length=100, verbose_name="版本号")),
                ("commit_hash", models.CharField(blank=True, max_length=100, verbose_name="提交哈希")),
                ("config_snapshot", models.JSONField(blank=True, default=dict, verbose_name="配置快照")),
                ("status", models.CharField(choices=[("queued", "排队中"), ("running", "打包中"), ("success", "成功"), ("failure", "失败"), ("canceled", "已取消")], default="queued", max_length=20, verbose_name="状态")),
                ("workspace_path", models.CharField(blank=True, max_length=1000, verbose_name="工作区路径")),
                ("log_path", models.CharField(blank=True, max_length=1000, verbose_name="日志路径")),
                ("artifact_info", models.JSONField(blank=True, default=list, verbose_name="产物信息")),
                ("duration", models.IntegerField(default=0, verbose_name="耗时毫秒")),
                ("error_message", models.TextField(blank=True, verbose_name="失败原因")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="结束时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("config", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tasks", to="package.packageconfig", verbose_name="打包配置")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="package_tasks", to="project.project", verbose_name="项目")),
                ("release", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="package_tasks", to="release.releaserecord", verbose_name="关联发布")),
                ("repository", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="package_tasks", to="repository.repository", verbose_name="仓库")),
                ("triggered_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="triggered_package_tasks", to=settings.AUTH_USER_MODEL, verbose_name="触发人")),
            ],
            options={
                "verbose_name": "打包任务",
                "verbose_name_plural": "打包任务",
                "db_table": "package_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="packageimage",
            index=models.Index(fields=["build_type", "is_active"], name="package_ima_build_t_0ac7d6_idx"),
        ),
        migrations.AddIndex(
            model_name="packageconfig",
            index=models.Index(fields=["project", "mode", "is_active"], name="package_con_project_7598ec_idx"),
        ),
        migrations.AddIndex(
            model_name="packageconfig",
            index=models.Index(fields=["repository", "auto_package_on_release"], name="package_con_reposit_137631_idx"),
        ),
        migrations.AddIndex(
            model_name="packagetask",
            index=models.Index(fields=["project", "status"], name="package_tas_project_f7e7b5_idx"),
        ),
        migrations.AddIndex(
            model_name="packagetask",
            index=models.Index(fields=["release", "status"], name="package_tas_release_7f5c5e_idx"),
        ),
        migrations.AddIndex(
            model_name="packagetask",
            index=models.Index(fields=["repository", "created_at"], name="package_tas_reposit_4fc379_idx"),
        ),
    ]
