# Generated by Django 5.0.14 on 2026-07-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageconfig',
            name='output_path',
            field=models.CharField(blank=True, default='dist', max_length=300, verbose_name='产物目录'),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='default_output_path',
            field=models.CharField(default='dist', max_length=300, verbose_name='默认产物目录'),
        ),
    ]
