# Generated by Django 5.0.14 on 2026-07-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_alter_package_output_path_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetask',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='进度百分比'),
        ),
        migrations.AddField(
            model_name='packagetask',
            name='stage_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='阶段信息'),
        ),
    ]
