# Generated by Django 5.0.14 on 2026-07-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0007_personal_only_svn_shared'),
        ('package', '0004_svn_push'),
        ('project', '0003_delete_projectintegration'),
        ('repository', '0006_gitlab_only_vendor'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='packageconfig',
            name='package_con_project_7598ec_idx',
        ),
        migrations.RenameField(
            model_name='packageconfig',
            old_name='local_script',
            new_name='custom_script',
        ),
        migrations.RemoveField(
            model_name='packageconfig',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='packagetask',
            name='mode',
        ),
        migrations.AddIndex(
            model_name='packageconfig',
            index=models.Index(fields=['project', 'is_active'], name='package_con_project_7598ec_idx'),
        ),
    ]
