# Generated by Django 5.0.14 on 2026-07-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_remove_packageconfig_package_con_project_7598ec_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageconfig',
            name='custom_script',
            field=models.TextField(blank=True, verbose_name='自定义打包脚本'),
        ),
    ]
