# Generated by Django 5.0.14 on 2026-07-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_alter_packageconfig_custom_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageimage',
            name='image_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='镜像名'),
        ),
        migrations.AddField(
            model_name='packageimage',
            name='image_tag',
            field=models.CharField(blank=True, max_length=300, verbose_name='镜像标签'),
        ),
        migrations.AddField(
            model_name='packageimage',
            name='registry_host',
            field=models.CharField(blank=True, max_length=300, verbose_name='镜像拉取地址'),
        ),
        migrations.AddField(
            model_name='packageimage',
            name='repository',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nexus 仓库名'),
        ),
        migrations.AddField(
            model_name='packageimage',
            name='source',
            field=models.CharField(choices=[('nexus', 'Nexus')], default='nexus', max_length=20, verbose_name='镜像来源'),
        ),
        migrations.AddIndex(
            model_name='packageimage',
            index=models.Index(fields=['source', 'is_active'], name='package_ima_source_2f3b1e_idx'),
        ),
    ]
