# Generated by Django 5.0.14 on 2026-07-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0007_packageimage_image_name_packageimage_image_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageimage',
            options={'ordering': ['-created_at'], 'verbose_name': '打包镜像', 'verbose_name_plural': '打包镜像'},
        ),
        migrations.RemoveIndex(
            model_name='packageimage',
            name='package_ima_build_t_0ac7d6_idx',
        ),
        migrations.RemoveField(
            model_name='packageconfig',
            name='build_type',
        ),
        migrations.RemoveField(
            model_name='packageimage',
            name='build_type',
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='source',
            field=models.CharField(choices=[('nexus', 'Nexus'), ('local', '本地')], default='nexus', max_length=20, verbose_name='镜像来源'),
        ),
        migrations.AlterField(
            model_name='packagetask',
            name='build_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='打包类型'),
        ),
        migrations.AddConstraint(
            model_name='packageimage',
            constraint=models.UniqueConstraint(fields=('source', 'registry_host', 'repository', 'image_name', 'image_tag'), name='package_image_unique_source_coord'),
        ),
    ]
