# Generated by Django 5.0.14 on 2026-07-28 08:17

from django.db import migrations, models


def migrate_script_entry_default(apps, schema_editor):
    """存量镜像记录的旧默认入口统一切换到新目录约定的 pack.sh。"""
    PackageImage = apps.get_model("package", "PackageImage")
    PackageImage.objects.filter(script_entry="/usr/local/bin/trace-ship-build").update(
        script_entry="/workspace/scripts/pack.sh"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0008_alter_packageimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageimage',
            name='script_entry',
            field=models.CharField(default='/workspace/scripts/pack.sh', max_length=500, verbose_name='镜像脚本入口'),
        ),
        migrations.RunPython(migrate_script_entry_default, migrations.RunPython.noop),
    ]
