# Generated by Django 5.0.14 on 2026-08-10 02:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0008_alter_credential_cred_type'),
        ('package', '0009_alter_packageimage_script_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='packageconfig',
            name='executor_type',
            field=models.CharField(choices=[('local_docker', '本地 Docker'), ('remote_windows', '远程 Windows')], default='local_docker', max_length=20, verbose_name='执行方式'),
        ),
        migrations.CreateModel(
            name='PackageNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='节点名称')),
                ('host', models.CharField(max_length=300, verbose_name='主机地址')),
                ('port', models.IntegerField(default=22, verbose_name='SSH 端口')),
                ('os_type', models.CharField(choices=[('windows', 'Windows')], default='windows', max_length=20, verbose_name='操作系统')),
                ('work_root', models.CharField(default='C:\\trace-ship\\workspaces', max_length=500, verbose_name='远程工作根目录')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_package_nodes', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_nodes', to='credential.credential', verbose_name='登录凭证')),
            ],
            options={
                'verbose_name': '打包节点',
                'verbose_name_plural': '打包节点',
                'db_table': 'package_node',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='packageconfig',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_configs', to='package.packagenode', verbose_name='远程打包节点'),
        ),
    ]
