# Generated by Django 5.0.14 on 2026-08-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0010_packageconfig_executor_type_packagenode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagenode',
            name='max_concurrency',
            field=models.IntegerField(default=1, verbose_name='最大并发打包数'),
        ),
    ]
