# Generated by Django 5.0.14 on 2026-08-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0011_packagenode_max_concurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetask',
            name='release_type',
            field=models.CharField(choices=[('formal', '正式版'), ('rc', 'RC 版'), ('beta', '测试版')], default='formal', max_length=20, verbose_name='发布类型'),
        ),
    ]
