# Generated by Django 5.0.14 on 2026-08-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0012_packagetask_release_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagenode',
            name='cpu_cores',
            field=models.IntegerField(default=0, verbose_name='构建可用 CPU 核数'),
        ),
        migrations.AddField(
            model_name='packagenode',
            name='cpu_priority',
            field=models.CharField(choices=[('normal', '正常'), ('belownormal', '低于正常'), ('low', '低')], default='belownormal', max_length=20, verbose_name='构建进程 CPU 优先级'),
        ),
    ]
