# Generated by Django 5.0.14 on 2026-08-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0013_packagenode_cpu_cores_packagenode_cpu_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageconfig',
            name='cpu_cores',
            field=models.IntegerField(default=0, verbose_name='构建可用 CPU 核数'),
        ),
        migrations.AddField(
            model_name='packageconfig',
            name='cpu_priority',
            field=models.CharField(blank=True, choices=[('normal', '正常'), ('belownormal', '低于正常'), ('low', '低')], default='', max_length=20, verbose_name='构建进程 CPU 优先级'),
        ),
        migrations.AddField(
            model_name='packageconfig',
            name='mem_limit_mb',
            field=models.IntegerField(default=0, verbose_name='构建内存上限（MB）'),
        ),
    ]
