# Generated by Django 5.0.14 on 2026-08-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0014_packageconfig_cpu_cores_packageconfig_cpu_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageconfig',
            name='auto_collect_output',
            field=models.BooleanField(default=False, help_text='构建完成后自动将产物目录内容归集到 artifacts，脚本无需手动拷贝', verbose_name='自动收集产物'),
        ),
    ]
