# Generated by Django 5.0.14 on 2026-08-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0015_packageconfig_auto_collect_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageconfig',
            name='cleanup_workspace',
            field=models.BooleanField(default=True, help_text='打包成功后自动清理远程节点工作目录（关闭可保留源码与产物用于调试，仅远程执行生效）', verbose_name='打包后清理工作区'),
        ),
    ]
