# Generated by Django：打包配置新增「自动压缩产物」开关
#
# 开启后构建完成时把产物目录内所有内容压缩为单个 zip 压缩包
# （命名：软件名-版本-日期），最终产物只保留这一个压缩包。
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("package", "0016_packageconfig_cleanup_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="packageconfig",
            name="auto_compress",
            field=models.BooleanField(
                default=False,
                verbose_name="自动压缩产物",
                help_text="构建完成后将产物目录内所有内容压缩为单个 zip 压缩包（命名：软件名-版本-日期）",
            ),
        ),
    ]
