# Generated by Django 5.0.14 on 2026-08-14 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0018_packageknowledge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='packageknowledge',
            index=models.Index(fields=['is_active', 'updated_at'], name='pkg_knowledge_active_upd_idx'),
        ),
    ]
