# Generated by Django 5.0.14 on 2026-08-17 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0019_packageknowledge_pkg_knowledge_active_upd_idx'),
        ('release', '0008_remove_releaserecord_jenkins_build'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetask',
            name='release',
            field=models.ForeignKey(blank=True, help_text='发布触发任务绑定发布记录；分支直打包任务该字段为空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_tasks', to='release.releaserecord', verbose_name='关联发布'),
        ),
    ]
