# Generated by Django 5.0.14 on 2026-08-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0020_alter_packagetask_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageconfig',
            name='clone_submodules',
            field=models.BooleanField(default=False, help_text='clone 时递归拉取 .gitmodules 子模块（完整克隆，便于后续提交推送）', verbose_name='拉取 Git 子模块'),
        ),
        migrations.AddField(
            model_name='packageconfig',
            name='inject_git_credential',
            field=models.BooleanField(default=False, help_text='将仓库凭证以 GIT_ASKPASS 方式注入打包容器/远程节点，打包脚本可自行执行 git push；凭证对脚本可见，仅在需要 push 时开启', verbose_name='注入 Git 凭证到构建环境'),
        ),
        migrations.AddField(
            model_name='packageconfig',
            name='svn_commit_mode',
            field=models.CharField(choices=[('new_dir', '新建版本目录'), ('overwrite', '覆盖式提交')], default='new_dir', help_text='新建版本目录：目标目录已存在时报错；覆盖式提交：目录已存在时镜像覆盖更新（新增/修改/删除同步）', max_length=20, verbose_name='SVN 提交模式'),
        ),
    ]
