# Generated by Django 5.0.14 on 2026-08-28 01:16

from django.db import migrations, models


def executor_type_to_remote_node(apps, schema_editor):
    """存量远程 Windows 配置迁为语义中性的 remote_node。"""
    PackageConfig = apps.get_model("package", "PackageConfig")
    PackageConfig.objects.filter(executor_type="remote_windows").update(executor_type="remote_node")
    # 未结束任务的配置快照同样固化 executor_type，需一并迁移，
    # 否则升级后 queued/running 任务会被当作本地 Docker 执行并绕过节点并发闸门
    PackageTask = apps.get_model("package", "PackageTask")
    for task in PackageTask.objects.filter(
        status__in=("queued", "running"), config_snapshot__executor_type="remote_windows"
    ):
        snapshot = task.config_snapshot
        snapshot["executor_type"] = "remote_node"
        task.config_snapshot = snapshot
        task.save(update_fields=["config_snapshot"])


def executor_type_back_to_remote_windows(apps, schema_editor):
    """回滚：remote_node 迁回 remote_windows。"""
    PackageConfig = apps.get_model("package", "PackageConfig")
    PackageConfig.objects.filter(executor_type="remote_node").update(executor_type="remote_windows")
    PackageTask = apps.get_model("package", "PackageTask")
    for task in PackageTask.objects.filter(
        status__in=("queued", "running"), config_snapshot__executor_type="remote_node"
    ):
        snapshot = task.config_snapshot
        snapshot["executor_type"] = "remote_windows"
        task.config_snapshot = snapshot
        task.save(update_fields=["config_snapshot"])


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0021_packageconfig_clone_submodules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageconfig',
            name='executor_type',
            field=models.CharField(choices=[('local_docker', '本地 Docker'), ('remote_node', '远程节点')], default='local_docker', max_length=20, verbose_name='执行方式'),
        ),
        migrations.AlterField(
            model_name='packagenode',
            name='os_type',
            field=models.CharField(choices=[('windows', 'Windows'), ('kylin', '麒麟 Linux')], default='windows', max_length=20, verbose_name='操作系统'),
        ),
        migrations.RunPython(executor_type_to_remote_node, executor_type_back_to_remote_windows),
    ]
