# Generated by Django 5.0.14 on 2026-08-28 07:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0022_alter_packageconfig_executor_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageConfigFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='package.packageconfig', verbose_name='打包配置')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_config_favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '打包配置收藏',
                'verbose_name_plural': '打包配置收藏',
                'db_table': 'package_config_favorite',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='packageconfigfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'config'), name='package_config_favorite_unique_user_config'),
        ),
    ]
