# Generated by Django 5.0.14 on 2026-08-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0023_packageconfigfavorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagenode',
            name='arch',
            field=models.CharField(choices=[('x86_64', 'x86 64位'), ('x86_32', 'x86 32位'), ('arm64', 'ARM 64位'), ('arm32', 'ARM 32位')], default='x86_64', max_length=20, verbose_name='芯片架构'),
        ),
    ]
