# Generated by Django 5.0.14 on 2026-09-10 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0024_packagenode_arch'),
        ('project', '0006_remove_productcomponent_uniq_product_component_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageconfig',
            name='product_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='package_configs', to='project.productcomponent', verbose_name='产品组件'),
        ),
    ]
