# Generated by Django 5.0.14 on 2026-09-17 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0029_rename_project_component_drop_redundant_fields'),
        ('project', '0008_rename_project_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageconfig',
            name='project_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_configs', to='project.projectcomponent', verbose_name='项目组件'),
        ),
    ]
