# Generated by Django 5.0.14 on 2026-09-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("package", "0030_alter_packageconfig_project_component"),
    ]

    operations = [
        migrations.AddField(
            model_name="packageconfig",
            name="svn_push_rc",
            field=models.BooleanField(
                default=False,
                help_text="发布后自动打包时，RC 版产物提交到 rc/版本号；关闭则不推送",
                verbose_name="RC 版提交 SVN",
            ),
        ),
        migrations.AddField(
            model_name="packageconfig",
            name="svn_push_beta",
            field=models.BooleanField(
                default=False,
                help_text="发布后自动打包时，测试版产物提交到 beta/版本号；关闭则不推送",
                verbose_name="测试版提交 SVN",
            ),
        ),
    ]
