# Generated by Django 5.0.14 on 2026-10-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0031_packageconfig_svn_push_rc_beta'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetask',
            name='source_ref',
            field=models.CharField(blank=True, max_length=200, verbose_name='实际源码拉取引用'),
        ),
    ]
