# Generated by Django 5.0.14 on 2026-06-24 09:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credential', '0002_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JenkinsJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('server_url', models.CharField(max_length=500, verbose_name='Jenkins 地址')),
                ('job_name', models.CharField(max_length=200, verbose_name='Jenkins Job 名')),
                ('credential_mode', models.CharField(choices=[('current_user', '当前用户'), ('specified_user', '指定用户'), ('fixed', '项目固定凭证'), ('global', '系统全局凭证')], default='fixed', max_length=20, verbose_name='凭证使用模式')),
                ('params_template', models.JSONField(blank=True, default=dict, verbose_name='参数模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jenkins_jobs', to='credential.credential', verbose_name='关联凭证')),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jenkins_jobs', to='project.projectintegration', verbose_name='外站绑定')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jenkins_jobs', to='project.project', verbose_name='项目')),
                ('specified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specified_jenkins_jobs', to=settings.AUTH_USER_MODEL, verbose_name='指定用户')),
            ],
            options={
                'verbose_name': 'Jenkins 任务',
                'verbose_name_plural': 'Jenkins 任务',
                'db_table': 'jenkins_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JenkinsBuild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queue_id', models.CharField(blank=True, max_length=100, verbose_name='队列号')),
                ('build_number', models.IntegerField(blank=True, null=True, verbose_name='构建号')),
                ('status', models.CharField(choices=[('queue', '排队中'), ('running', '构建中'), ('success', '成功'), ('failure', '失败'), ('aborted', '中止')], default='queue', max_length=20, verbose_name='状态')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='构建参数')),
                ('log_url', models.CharField(blank=True, max_length=500, verbose_name='日志地址')),
                ('artifact_info', models.JSONField(blank=True, default=list, verbose_name='产物信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='jenkins.jenkinsjob', verbose_name='Jenkins 任务')),
            ],
            options={
                'verbose_name': 'Jenkins 构建记录',
                'verbose_name_plural': 'Jenkins 构建记录',
                'db_table': 'jenkins_build',
                'ordering': ['-created_at'],
            },
        ),
    ]
