# Generated by Django 5.0.14 on 2026-06-25 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins', '0001_initial'),
        ('repository', '0003_remove_repository_integration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jenkinsjob',
            name='integration',
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jenkins_jobs', to='repository.repository', verbose_name='关联仓库'),
        ),
    ]
