# Generated by Django 5.0.14 on 2026-07-02 03:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0004_retire_global_scope'),
        ('jenkins', '0004_jenkinsjob_credential_mode_simplify'),
        ('project', '0003_delete_projectintegration'),
        ('release', '0007_releaserecord_config_change_doc_and_more'),
        ('repository', '0004_repository_credential_mode_simplify'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsbuild',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jenkins_builds', to='release.releaserecord', verbose_name='关联发布'),
        ),
        migrations.AddField(
            model_name='jenkinsbuild',
            name='stage_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='阶段信息'),
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='auto_build_on_release',
            field=models.BooleanField(default=False, verbose_name='发布后自动打包'),
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='build_path',
            field=models.CharField(blank=True, default='.', max_length=300, verbose_name='构建目录'),
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='build_type',
            field=models.CharField(choices=[('web', 'Web'), ('qt', 'Qt'), ('custom', '自定义')], default='web', max_length=20, verbose_name='打包类型'),
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='config_mode',
            field=models.CharField(choices=[('simple', '简单模式'), ('advanced', '高级模式')], default='advanced', max_length=20, verbose_name='配置模式'),
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='managed_job',
            field=models.BooleanField(default=False, verbose_name='系统托管 Job'),
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='output_path',
            field=models.CharField(blank=True, default='dist', max_length=300, verbose_name='输出目录'),
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='pipeline_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Pipeline 配置'),
        ),
        migrations.CreateModel(
            name='JenkinsBuildPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='预设名称')),
                ('build_type', models.CharField(choices=[('web', 'Web'), ('qt', 'Qt'), ('custom', '自定义')], default='web', max_length=20, verbose_name='打包类型')),
                ('image', models.CharField(max_length=500, verbose_name='Docker 镜像')),
                ('script_entry', models.CharField(default='/usr/local/bin/trace-ship-build', max_length=500, verbose_name='脚本入口')),
                ('default_build_path', models.CharField(default='.', max_length=300, verbose_name='默认构建目录')),
                ('default_output_path', models.CharField(default='dist', max_length=300, verbose_name='默认输出目录')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Jenkins 打包预设',
                'verbose_name_plural': 'Jenkins 打包预设',
                'db_table': 'jenkins_build_preset',
                'ordering': ['build_type', '-created_at'],
                'indexes': [models.Index(fields=['build_type', 'is_active'], name='jenkins_bui_build_t_2456a1_idx')],
            },
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='build_preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jenkins.jenkinsbuildpreset', verbose_name='打包预设'),
        ),
        migrations.AddIndex(
            model_name='jenkinsjob',
            index=models.Index(fields=['project', 'config_mode', 'is_active'], name='jenkins_job_project_2469ea_idx'),
        ),
        migrations.AddIndex(
            model_name='jenkinsjob',
            index=models.Index(fields=['repository', 'auto_build_on_release'], name='jenkins_job_reposit_8d11d2_idx'),
        ),
    ]
