# Generated by Django：Jenkins 模块下线，删除全部模型
#
# 本 app 仅保留为迁移 tombstone（release.0001 历史迁移依赖 jenkins app），
# 模型与表在此迁移中删除，业务代码已移除。

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jenkins", "0005_jenkinsbuild_release_jenkinsbuild_stage_info_and_more"),
        # 需先移除 ReleaseRecord.jenkins_build 外键，才能删除 JenkinsBuild
        ("release", "0008_remove_releaserecord_jenkins_build"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JenkinsBuild",
        ),
        migrations.DeleteModel(
            name="JenkinsJob",
        ),
        migrations.DeleteModel(
            name="JenkinsBuildPreset",
        ),
    ]
